# image
image: Visual Studio 2015

# build platform
platform: x64

# clone directory
clone_folder: c:\xmr-stak

install:
  - mkdir c:\xmr-stak-dep
  - curl -sL https://github.com/fireice-uk/xmr-stak-dep/releases/download/v2/xmr-stak-dep.zip -o xmr-stak-dep.zip
  - 7z x xmr-stak-dep.zip -o"c:\xmr-stak-dep" -y > nul
  - appveyor DownloadFile  https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda_9.1.85_win10 -FileName cuda_9.1.85_win10.exe
  - cuda_9.1.85_win10.exe -s compiler_9.0 cudart_9.0
  - set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;%PATH%
  - nvcc -V

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\xmr-stak
  - mkdir build
  - cd build
  - set CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl;
  - cmake -G "Visual Studio 14 2015 Win64" -T v140,host=x64 .. -DCUDA_ARCH=30
  - cmake --build . --config Release --target install

test_script:
  - cd c:\xmr-stak\build\bin\Release
  - dir
  - copy C:\xmr-stak-dep\openssl\bin\* .
  - 7z a myapp.zip *
  - set XMRSTAK_NOWAIT=1
  - xmr-stak.exe --help --noUAC

artifacts:
  - path: build\bin\Release\myapp.zip
    name: MyApp
